version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3309:3306
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=TheBlackThing
      - MYSQL_ROOT_PASSWORD=dot
      - MYSQL_USER=blackDot
      - MYSQL_PASSWORD=dot

  nodejs:
    restart: always
    build:
      context: ./Docker
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    volumes:
      - ./Docker/:/Docker
      - ./Docker/node_modules/:/Docker/node_modules
    depends_on:
      - mysql

volumes:
  dbdata:
