version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    container_name: mysql_db
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=TheBlackThing
      - MYSQL_ROOT_PASSWORD=dot
      - MYSQL_USER=blackDot
      - MYSQL_PASSWORD=dot

  nodejs:
    restart: always
    container_name: server
    build:
      context: ./Docker
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./Docker/:/Docker
    depends_on:
      - mysql

volumes:
  dbdata:
