version: '3.8'
services:
  server:
    depends_on:
      - mysqlDB
    ports:
      - 80:80
    build: ./Downloads
    restart: unless-stopped
    
    # combine below two together makes `-it` option when you use `docker exec -it`
    stdin_open: true # `-i`
    tty: true # `-t`

    networks:
      - mysql_db
  mysqlDB:
    image: mysql
    restart: unless-stopped
    env_file:
      - Downloads/.env
    container_name: mysql_db
    ports:
      - 3306:3306
    #environment:
      #- MYSQL_USER=${MYSQL_USER}
      #- MYSQL_DATABASE=${MYSQL_DATABASE}
      #- MYSQL_CONTAINER_NAME=${MYSQL_CONTAINER_NAME}
      #- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      #- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      #- MYSQL_PASSWORD=${MYSQL_PASSWORD}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - db:/var/lib/mysql  # -v option
    networks:
      - mysql_db
volumes:
    db:
networks:
    mysql_db: